# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            PPT PC Tetris League
tagline:          'PPT Competitive Tetris League'
description:      'Organized by <a href="https://twitter.com/saltedbread" target="_blank">@saltedbread</a>.'
url:              saltedbread.github.io
baseurl:          '/'

author:
  name:           'saltedbread'
  url:            https://twitter.com/saltedbread

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/saltedbread/saltedbread.github.io.git

plugins:
 - jekyll-paginate
 - jekyll-gist
 - redcarpet
 - pygments.rb
